version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.volume/:/files
  uploader:
    build:
      context: ./uploader
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./.volume/:/files
    environment:
      UPLOAD_PATH: '/files'
      ACCESS_TOKEN: 'uploadtoken'
